"""Rebuild the deterministic shader textures (Pillow, NumPy, SciPy, fontTools).

The reference soundtrack and native recording are prepared separately by
prepare_media.py; they are not synthesized or baked into the textures.
"""

from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
from fontTools.pens.basePen import BasePen
from fontTools.svgLib.path import parse_path

ROOT = Path(__file__).resolve().parents[1]
MEDIA = ROOT / "media"
SIZE = (1920, 1080)


def encode_sdf(filename, mask):
    inside = np.asarray(mask) > 127
    distance = distance_transform_edt(~inside) - distance_transform_edt(inside)
    encoded = np.rint(np.clip(0.5 + distance / 512, 0, 1) * 65535).astype(np.uint16)
    rgb = np.stack([encoded >> 8, encoded & 255, np.asarray(mask)], axis=-1).astype(np.uint8)
    Image.fromarray(rgb).save(MEDIA / filename)



class RasterPen(BasePen):
    """Flatten the repository's own vector wordmark into reproducible shader masks."""
    def __init__(self, draw, scale, offset):
        super().__init__(None)
        self.draw, self.scale, self.offset = draw, scale, offset
        self.points = []

    def _moveTo(self, p):
        self.points = [p]

    def _lineTo(self, p):
        self.points.append(p)

    def _qCurveToOne(self, control, end):
        start = self._getCurrentPoint()
        for t in np.linspace(0, 1, 24)[1:]:
            self.points.append(tuple((1-t)**2*a+2*(1-t)*t*b+t*t*c for a,b,c in zip(start,control,end)))

    def _curveToOne(self, c1, c2, end):
        start = self._getCurrentPoint()
        for t in np.linspace(0, 1, 32)[1:]:
            self.points.append(tuple((1-t)**3*a+3*(1-t)**2*t*b+3*(1-t)*t*t*c+t**3*d for a,b,c,d in zip(start,c1,c2,end)))

    def _closePath(self):
        points = [(x*self.scale+self.offset[0],y*self.scale+self.offset[1]) for x,y in self.points]
        self.draw.polygon(points,fill=255)

    def _endPath(self):
        self._closePath()


def brand_assets():
    repo = ROOT.parents[1]
    mark = ET.parse(repo/'landing/brand/fframes-mark.svg').getroot()
    mask = Image.new('L', SIZE)
    pen = RasterPen(ImageDraw.Draw(mask),2.65,(280,-150))
    for path in mark.findall('{http://www.w3.org/2000/svg}path'):
        parse_path(path.attrib['d'],pen)
    encode_sdf('fframes-sdf.png',mask)


def catalog():
    names = ['Glass','Chrome','CarbonFiber','FlowingGradient','Godrays','Obsidian',
             'ThinFilm','Emboss','Ascii','Halftone','Particles','Aurora',
             'Shader::sksl','ShaderUniforms','Shader::shadertoy','Video','Scene',
             'Frame','Metal','Vulkan','SVG','Timeline','Prism','Holographic']
    canvas = Image.new('RGB',(4096,2048),'#08080a')
    draw = ImageDraw.Draw(canvas)
    font = ImageFont.truetype(str(MEDIA/'JetBrainsMono-Regular.ttf'),36)
    portal = None
    tiles = []
    portal_tile = None
    for row in range(16):
        x = -180 + [0,160,-65,95][row%4]
        col = 0
        while x < 4096:
            name = names[(row*5+col*3)%len(names)]
            if row == 8 and col == 6: name = 'FlowingGradient'
            width = max(450,int(font.getlength(name))+200)
            y = row*128
            tiles.append((x+5, y+5, width-12, 114))
            draw.rounded_rectangle((x+5,y+5,x+width-7,y+119),radius=12,
                                   fill='#1b1b1d',outline='#27272a',width=2)
            draw.line((x+20,y+7,x+width-24,y+7), fill='#2e2e31',width=1)
            draw.text((x+24,y+42),'<',font=font,fill='#80cbd4')
            draw.text((x+116,y+42),name,font=font,fill='#ddc88f')
            draw.text((x+width-59,y+42),'/>',font=font,fill='#80cbd4')
            # Small procedural material swatches, at 2x resolution for clean circles.
            yy,xx = np.mgrid[-1:1:96j,-1:1:96j]
            r=np.sqrt(xx*xx+yy*yy)
            phase=(row*5+col*3)*.17
            folds=np.sin(xx*3+np.sin(yy*4+phase))*np.cos(yy*3-phase)
            shade=.35+.65*np.sqrt(np.clip(1-r*r,0,1))
            palette=.5+.5*np.cos((folds*.24+phase+np.array([0,.33,.67])[:,None,None])*2*np.pi)
            highlight=np.exp(-((xx+.30)**2+(yy+.43)**2)*16)
            rgb=(palette*.72+.09)*shade+highlight*.5
            rgba=np.dstack([np.moveaxis(np.clip(rgb,0,1),0,-1),np.clip((1-r)*48,0,1)])
            icon=Image.fromarray(np.uint8(rgba*255),'RGBA').resize((48,48),Image.Resampling.LANCZOS)
            canvas.paste(icon,(x+61,y+40),icon)
            if row == 8 and col == 6:
                portal=(x+85,y+64)
                portal_tile=len(tiles)-1
            x += width
            col += 1
    canvas.save(MEDIA/'catalog.png')
    layout = '// Generated by tools/assets.py together with media/catalog.png.\n'
    layout += f'pub(super) const PORTAL_TILE: usize = {portal_tile};\n'
    layout += f'pub(super) const PORTAL: [f32; 2] = [{portal[0]}.0, {portal[1]}.0];\n'
    layout += f'pub(super) const RECTS: [[f32; 4]; {len(tiles)}] = [\n'
    layout += ''.join('    [' + ', '.join(f'{v}.0' for v in tile) + '],\n' for tile in tiles)
    layout += '];\n'
    (ROOT/'src/catalog_layout.rs').write_text(layout)
    print('Catalog portal:',portal)


def glyph_atlas():
    chars = '@%#08XOox*+=-:. '
    atlas = Image.new('L', (512,512))
    draw = ImageDraw.Draw(atlas)
    font = ImageFont.truetype(str(MEDIA/'JetBrainsMono-Regular.ttf'),96)
    for i, char in enumerate(chars):
        box = draw.textbbox((0,0),char,font=font)
        x=i%4*128+(128-box[2]+box[0])/2-box[0]
        y=i//4*128+(128-box[3]+box[1])/2-box[1]
        draw.text((x,y),char,font=font,fill=255)
    atlas.convert('RGB').save(MEDIA/'glyph-atlas.png')


def binary_atlas():
    atlas = Image.new('L', (256,128))
    draw = ImageDraw.Draw(atlas)
    font = ImageFont.truetype(str(MEDIA/'JetBrainsMono-Regular.ttf'),144)
    for i, char in enumerate('01'):
        box = draw.textbbox((0,0),char,font=font)
        x=i*128+(128-box[2]+box[0])/2-box[0]
        y=(128-box[3]+box[1])/2-box[1]
        draw.text((x,y),char,font=font,fill=255)
    atlas.convert('RGB').save(MEDIA/'binary-atlas.png')


if __name__ == "__main__":
    brand_assets()
    catalog()
    glyph_atlas()
    binary_atlas()
